drop table if exists users cascade;
drop table if exists organisations cascade;
drop table if exists accountStatus cascade;
drop table if exists roles cascade;
drop table if exists bids cascade;
drop table if exists auctions cascade;
drop table if exists reports cascade;
drop table if exists executions cascade;
drop extension if exists citext cascade;
